  version: '3'
  services:
    web:
      build:
        context: .
      ports:
        - 8000:80
      volumes: ['./web:/var/www/html']
      networks:
        - laravel

    mysql-db:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      container_name: mysql-db
      volumes: ['./mysql_data:/var/lib/mysql']
      environment:
        - MYSQL_ROOT_PASSWORD=mysqlrootpassword
        - MYSQL_DATABASE=laravel
        - MYSQL_USER=laravel
        - MYSQL_PASSWORD=mysqlpassword
      networks:
         - laravel
  networks:
    laravel:
  volumes:
    web:
    mysql_data: