  version: '3'
  services:
    mysql-db:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      container_name: mysql-db
      restart: unless-stopped      
      environment:
        - MYSQL_ROOT_PASSWORD=mysqlrootpassword
        - MYSQL_DATABASE=laravel
        - MYSQL_USER=laravel
        - MYSQL_PASSWORD=mysqlpassword
      networks:
         - laravel

    web:
      build:
        context: .
      ports:
        - 8000:80
      volumes: ['./web:/var/www/html']
      depends_on:
        - mysql-db
      networks:
        - laravel
           
  networks:
    laravel:
  volumes:    
    web:
