  version: '3'
  services:
    web:
      build:
        context: .
      ports:
        - 8000:80
      volumes:
        - ./web:/app

    mysql-db:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      container_name: mysql-db
      volumes:
        - ./mysql_data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=mysqlrootpassword
        - MYSQL_DATABASE=laravel
        - MYSQL_USER=root
        - MYSQL_PASSWORD=mysqlpassword
           

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - mysql-db
      environment:
        PMA_HOST: mysql-db
        MYSQL_ROOT_PASSWORD: mysqlrootpassword      
      ports:
        - '1001:80'
         


