  version: '3.5'
  services:
    mysql-db:
      image: mysql:5.7
      # command: --default-authentication-plugin=mysql_native_password      
      container_name: mysql-db
      restart: unless-stopped            
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      networks:
         - laravel

    web:
      build:
        context: .
      ports:
        - 8000:8000
      volumes: ['./web:/app']
      depends_on:
        - mysql-db
        - redis
      networks:
        - laravel
           
    redis:
      image: redis
      ports:
        - 6379:6379
      networks:
        - laravel           
           
  networks:
    laravel:
  volumes:    
    web:    