  version: '3'
  services:
    web:
      image: puskartrital/laravel-production:latest
      ports:
        - 8000:8000
      volumes:
        - ./:/app      

    mysql-db:
      image: mysql:5.7
      container_name: mysql-db
      volumes:
        - ./mysql_data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=mysqlrootpassword
        - MYSQL_DATABASE=laravel
        - MYSQL_USER=root
        - MYSQL_PASSWORD=mysqlpassword
           

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - mysql-db
      environment:
        PMA_HOST: mysql-db
        MYSQL_ROOT_PASSWORD: mysqlrootpassword      
      ports:
        - '1001:80'
         


